config/routes.rb
 Socialist::Application.routes.draw do
  get "profiles/show"

  devise_for :users
  devise_scope :user do
    get "register", to: "devise/registrations#new", as: :register
    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
  end

  resources :user_friendships

  resources :statuses
  get "updates", to: "statuses#index", as: :updates

  get "/:id", to: "profiles#show", as: :profile

  root to: "statuses#index"
end

app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id

  belongs_to :user

  validates :content, presence: true, length: { minimum: 2 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  has_many :statuses
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name,  presence: true,
                            uniqueness: true, 
                            format: {
                              with: /\A[a-zA-Z0-9_-]+\Z/,
                              message: "Must be formatted correctly"
                            }

  def full_name
    first_name + " " + last_name
  end

  def to_param
    profile_name
  end

  def gravatar_url
    normalized_email = email.strip.downcase
    hash = Digest::MD5.hexdigest(normalized_email)

    "http://gravatar.com/avatar/#{hash}"
  end
end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'

  attr_accessible :user, :friend, :user_id, :friend_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.all
      render action: :show
    else
      render file: 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = current_user.statuses.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = current_user.statuses.find(params[:id])
    if params[:status] && params[:status].has_key?(:user_id)
      params[:status].delete(:user_id)
    end
    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
  before_filter :authenticate_user!, only: [:new]
  def new
    if params[:friend_id]
      @friend = User.where(profile_name: params[:friend_id]).first
      raise ActiveRecord::RecordNotFound if @friend.nil?
      @user_friendship = current_user.user_friendships.new(friend: @friend)
    else
      flash[:error] = "Friend required"
    end

  rescue ActiveRecord::RecordNotFound
    render file: 'public/404', status: :not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type
    when :alert
      "alert-warning"
    when :notice
      "alert-success"
    when :error
      "alert-danger"
    else
      ""
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Socialist", root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "All Statuses", updates_path, :class => "active" %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if user_signed_in? %>
              <li><%= link_to "Hello #{current_user.full_name}", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", logout_path %></li>
            <% else %>
              <li><%= link_to "Sign in", login_path %></li>
              <li><%= link_to "Sign up", register_path %></li>
            <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="flashNotice">
    <% flash.each do |type, message| %>
      <div class="alert <%= flash_class type %>">
        <button class="close" type="button", data-dismiss="alert"></button>
        <%= message %>
      </div>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/profiles/show.html.erb
<div class="container">
  <div class="page-header">
    <h1><%= @user.full_name %></h1>
    <%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn btn-primary' %>
  </div>

  <% if @statuses %>
    <% @statuses.each do |status| %>
      <div class="well">
        <%= status.content %>
        <br>
        <%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
      </div>
    <% end %>
  <% end %>
</div>

app/views/statuses/_form.html.erb
<%= form_for @status, :html => {:class => "form-horizontal"} do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-2">
      <%= f.label :content %><br />
    </div>
    <div class="col-sm-10">
      <%= f.text_area :content, rows: 3, class: "form-control" %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<div class="container">
  <h1>Editing status</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @status %> |
  <%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>All of the Statuses</h1>
  </div>

  <%= link_to "Post a new Status", new_status_path, class: "btn btn-primary" %>

  <hr>

  <% @statuses.each do |status| %>
    <div class="status">
      <div class="row">
        <div class="col-md-1">
        <%= link_to image_tag(status.user.gravatar_url), profile_path(status.user) %>
        </div>
        <div class="col-md-7">
          <div class="spanStatus">
            <strong><%= status.user.full_name %></strong> | a.k.a (<%= status.user.profile_name %>)
            <p><%= status.content %></p>
            <div class="meta">
              <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
              <span class="admin">
              | <%= link_to "Edit", edit_status_path(status) %> | 
                <%= link_to "Delete", status, method: :delete, data: {confirm: "Are You Sure?"} %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/statuses/new.html.erb
<div class="container">
  <h1>New status</h1>
  <div class="row-fluid">
    <div class="span4 well">
      <%= render 'form' %>
    </div>
  </div>

  <%= link_to 'Back', statuses_path %>
</div>

app/views/statuses/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @status.user.full_name %> | a.k.a (<%= @status.user.profile_name %>)
  </p>

  <p>
    <b>Content:</b>
    <%= @status.content %>
  </p>


  <%= link_to 'Edit', edit_status_path(@status) %> |
  <%= link_to 'Back', statuses_path %>
</div>

app/views/user_friendships/new.html.erb
<div class="container">
  <% if @friend %>
    <h1><%= @friend.full_name %></h1>

    <p>Do you really want to friend <%= @friend.full_name %></p>

    <%= form_for @user_friendship, method: :post do |f| %>
      <div class="form form-actions">
      <%= f.hidden_field :friend_id, value: @friend %>
        <%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
        <%= link_to "Cencel", profile_path(@friend), class: 'btn btn-warning' %>
      </div>
    <% end %>
  <% end %>
</div>